name: Super-Linter

on:
  pull_request:
    branches: [main, development, qa]
    paths:
      - '**.js'
      - '**.java'
      - '**.py'
    types: [opened, synchronize, reopened]

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Run Super Linter
        uses: github/super-linter@v5
        env:
          DEFAULT_BRANCH: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          LINTER_COMMENT: true
          LOG_LEVEL: WARN
